#!/bin/sh
# script called to package up final jar files; only from firefox/makefile
#
#   Copyright 2004 Kevin P. Scannell
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.

if [ $# -ne 1 ]; then
	echo 'Usage: mozdist <englishjarnoextension>'
 	exit
fi
IRISHJAR=`echo "${1}" | sed 's/en/ga/; s/US/IE/'`
ENGLISHPREF=`echo "${1}" | sed 's/win/US/; s/mac/US/; s/unix/US/'`
IRISHPREF=`echo "${ENGLISHPREF}" | sed 's/en/ga/; s/US/IE/'`
rm -fR "${IRISHPREF}"
mkdir "${IRISHPREF}"
po2moz -i "${IRISHPREF}po" -o "${IRISHPREF}" -t "${ENGLISHPREF}"
bash sedtweaks
if echo "${1}" | egrep '^browser' > /dev/null
then
	cat bookmarks-ga.html | iconv -f iso88591 -t utf8 > ${IRISHPREF}/profile/bookmarks.html
	(cd eile; cp -Rf * ../${IRISHPREF})
else
	(cd eile-tk; cp -Rf * ../${IRISHPREF})
fi
rm -f "${IRISHJAR}.jar"
jar cvf "${IRISHJAR}.jar" "${IRISHPREF}"
