#!/bin/sh
# script called to package up final jar files; only from firefox/makefile
#
#   Copyright 2004 Kevin P. Scannell
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.

if [ $# -ne 1 ]; then
	echo 'Usage: mozdist <englishjarnoextension>'
 	exit
fi
IRISHJAR=`echo "${1}" | sed 's/en-US/ga-IE/'`
PACK=`echo "${1}" | sed 's/-en-US//'`
rm -fR "${IRISHJAR}"
mkdir "${IRISHJAR}"
po2moz -i "${IRISHJAR}po" -o "${IRISHJAR}" -t "${ENGLISHJAR}"
bash sedtweaks
if echo "${1}" | egrep '^browser' > /dev/null
then
	cat aistr.txt | sed 's/.*/<em:contributor>&<\/em:contributor> /' | tr -d "\n" | sed 's/^/#define MOZ_LANGPACK_CONTRIBUTORS /' | iconv -f iso-8859-1 -t utf8 > aistr.8.txt
	cat bookmarks-ga.html | iconv -f iso88591 -t utf8 > ${IRISHJAR}/profile/bookmarks.html
	(cd eile; cp -Rf * ../${IRISHJAR};)
	cat installer-ga.inc | iconv -f iso-8859-1 -t utf8 > ${IRISHJAR}/installer/installer.inc
	sed -i '/MOZ_LANGPACK_CONTRIBUTORS/r aistr.8.txt' ${IRISHJAR}/defines.inc
	sed -i '/^# /d' ${IRISHJAR}/defines.inc
	rm -f aistr.8.txt
fi
if echo "${1}" | egrep '^toolkit' > /dev/null
then
	(cd eile-tk; cp -Rf * ../${IRISHJAR})
fi
rm -f "${IRISHJAR}.jar"
jar cvf "${IRISHJAR}.jar" "${IRISHJAR}"
mv -f "${IRISHJAR}" "${PACK}"
cp -Rf ${PACK} "${HOME}/seal/moz/l10n/ga-IE"
mv -f "${PACK}" "${IRISHJAR}"
