#!/bin/sh
# script that translates the files in the given English directory
# (gotten directly from CVS or by unpacking a jar) using the compendium
# defined in the variable UTFCOMP below.  Only called from firefox/makefile
#   Result is a temporary directory ending in "po" with a bunch of po's in it.
#   This directory is packaged up using mozdist.
#
#  Copyright 2004 Kevin P. Scannell
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.


if [ $# -ne 2 ]; then
	echo 'Usage: moznua <englishjarnoextension> <currentcompendiumversion>'
 	exit
fi
VERSION="${2}"
UTFCOMP="firefox-${VERSION}.po"
rm -f aistriuchan.log
IRISHPREF=`echo "${1}" | sed 's/en-US/ga-IE/'`
rm -Rf "${IRISHPREF}po"
mkdir "${IRISHPREF}po"
moz2po -P --progress=verbose -i "${1}" -o "${IRISHPREF}po"
find "${IRISHPREF}po" -name '*.pot' |
while read pofile
do
	FILENAMEBASE=`echo "${pofile}" | sed 's/\(.*\)\.pot$/\1/'`
	echo "Translating ${FILENAMEBASE}.po..."
	TEMPPOT=`mktemp`
	msguniq "${pofile}" > ${TEMPPOT}
	if msgmerge -N -C "${UTFCOMP}" -o "${FILENAMEBASE}.po" /dev/null "${TEMPPOT}" > /dev/null 2>&1
	then
		echo "merged fine."
	else
		echo "PROBLEM TRANSLATING ${pofile}!!!" >> aistriuchan.log
		msgmerge -N -C "${UTFCOMP}" -o "${FILENAMEBASE}.po" /dev/null "${TEMPPOT}" > aistriuchan.log 2>&1
	fi
#	Pofake ${FILENAMEBASE}.po | msgcat - > tempe.po
#	mv tempe.po ${FILENAMEBASE}.po
	echo
	rm -f ${TEMPPOT} ${pofile}
done
