#!/bin/sh
# script that translates the files in the given English directory
# (gotten directly from CVS or by unpacking a jar) using the compendium
# defined in the variable UTFCOMP below.  Only called from firefox/makefile
#   Result is a temporary directory ending in "po" with a bunch of po's in it.
#   This directory is packaged up using mozdist.
#
#  Copyright 2004 Kevin P. Scannell
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.


if [ $# -ne 2 ]; then
	echo 'Usage: moznua <englishjarnoextension> <currentcompendiumversion>'
 	exit
fi
VERSION="${2}"
UTFCOMP="mozilla-${VERSION}.po"
rm -f aistriuchan.log
IRISHPREF=`echo "${1}" | sed 's/en-US/ga-IE/'`
MSGMERGE="msgmerge -N"
# MSGMERGE="msgmerge"
rm -Rf "${IRISHPREF}po"
mkdir "${IRISHPREF}po"
#PYTHONPATH="/home/kps/seal/installed-local/translate-toolkit-0.9" moz2po -P --progress=verbose -i "${1}" -o "${IRISHPREF}po"
moz2po -P --progress=verbose -i "${1}" -o "${IRISHPREF}po"
if [ $1 = "gaia-en-US" ]
then
	UTFCOMP="gaia-trunk.ga.po"
fi
if [ $1 = "dom-en-US" ]
then
        sed -i 's/image.*cannot/image \\"%S\\" cannot/' "${IRISHPREF}po/chrome/layout/MediaDocument.properties.pot"
fi
if [ $1 = "browser-en-US" ]
then
        rm -f "${IRISHPREF}po/chrome/help/*.xhtml.pot"
fi
if [ $1 = "toolkit-en-US" ]
then
#       sed -i '/^#: VK_SHIFT/{N; s/msgid .*/msgid "\\\\u0005"/}; /^#: VK_META/{N; s/msgid .*/msgid "\\\\u0011"/}; /^#: VK_ALT/{N; s/msgid .*/msgid "\\\\u0007"/}; /^#: VK_CONTROL/{N; s/msgid .*/msgid "\\\\u0006"/}' ${IRISHPREF}po/chrome/global-platform/mac/platformKeys.properties.pot
        rm -f ${IRISHPREF}po/chrome/mozapps/help/*.xhtml.pot
fi
find "${IRISHPREF}po" -name 'region.properties.pot' | xargs rm -f
find "${IRISHPREF}po" -name '*.pot' |
while read pofile
do
	FILENAMEBASE=`echo "${pofile}" | sed 's/\(.*\)\.pot$/\1/'`
	echo "Translating ${FILENAMEBASE}.po using compendium ${UTFCOMP}..."
	TEMPPOT=`mktemp`
	msguniq "${pofile}" > ${TEMPPOT}
	if $MSGMERGE -C "${UTFCOMP}" -o "${FILENAMEBASE}.po" /dev/null "${TEMPPOT}" > /dev/null 2>&1
	then
		echo "merged fine."
		pocat "${FILENAMEBASE}.po" > ${TEMPPOT}  # these lines clean it up - only important, as far as I know, for mail-en-US/chrome/messenger/featureConfigurator.dtd
		mv ${TEMPPOT} "${FILENAMEBASE}.po"
		echo "moved to ${FILENAMEBASE}.po"
	else
		echo "PROBLEM TRANSLATING ${pofile}!!!" >> aistriuchan.log
		$MSGMERGE -C "${UTFCOMP}" -o "${FILENAMEBASE}.po" /dev/null "${TEMPPOT}" > aistriuchan.log 2>&1
	fi
# Pofake stuff not needed with latest po2moz....
#	Pofake ${FILENAMEBASE}.po | msgcat --no-wrap - > tempe.po
#	sed -i '/^msgid "contains"/s/.*/#: 0\n&/' tempe.po
#	mv tempe.po ${FILENAMEBASE}.po
	rm -f ${TEMPPOT} ${pofile}
done
