#!/bin/bash
#  Usage: mymsgmerge compendium.po tofill.pot output.po
#  First two should remain unchanged.
#
#  Copyright 2004 Kevin P. Scannell
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.

if msgmerge -C "${1}" -o "${3}" /dev/null "${2}" > /dev/null 2>&1
then
	echo "merged fine."
	exit 0
else
	rm -f "${3}"
	TEMPFILE=`mktemp`
	HACKEDUP=`mktemp`
	msgmerge -C "${1}" /dev/null "${2}" 2> "${TEMPFILE}"
	sed -i -n '/duplicate message/{s/^[^:]*:\([0-9]*\).*/\1/; p}' "${TEMPFILE}"
	cp "${2}" "${HACKEDUP}"
	cat "${TEMPFILE}" | 
	while read lineno
	do
		sed -i "${lineno}s/^/# X/" "${HACKEDUP}"
		sed -i "$((${lineno}+1))s/^/# X/" "${HACKEDUP}"
	done
	if msgmerge -C "${1}" -o "${3}" /dev/null "${HACKEDUP}"
	then
		egrep -n '^# Xmsgid' "${3}" | sed 's/^\([0-9]*\):.*/\1/' > "${TEMPFILE}"
		cat "${TEMPFILE}" | 
		while read lineno
		do
			MSGID=`sed -n "${lineno}p" "${3}" | sed 's/^# X//'`
			FIRST=`grep -m 1 -n -e "${MSGID}" "${3}" | sed 's/^\([0-9]*\):.*/\1/'`
			MSGSTR=`sed -n "$((${FIRST}+1))p" "${3}"`
			sed -i "${lineno}s/^# Xmsg/msg/" "${3}"
			sed -i "$((${lineno}+1))s/.*/${MSGSTR}/" "${3}"
		done
	else
		echo "PROBLEM TRANSLATING ${3}!!!" >> ../aistriuchan.log
	fi
fi
