#!/bin/bash
#  ASCII ONLY
PONAME='trunk'
SRCDIR='moz-aurora'
ANSEO=${HOME}/gaeilge/gnu/mozilla/gaeilge/src

# commit any outstanding changes to PO file
cvs commit -m "outstanding changes before sync" firefox-${PONAME}.ga.po tbird-${PONAME}.ga.po calendar-${PONAME}.ga.po

cd ${HOME}/seal/$SRCDIR/ga-IE
hg up
hg pull -u

cd ${HOME}/seal/$SRCDIR/mozilla-aurora
hg pull
hg update -c

cd ${HOME}/seal/$SRCDIR/comm-aurora
hg pull
hg update -c

cd ${HOME}/seal/gaia/en-US
hg pull
hg update -c

cd ${ANSEO}
cat ${PONAME}.txt | sed 's/$/-en-US/' | xargs rm -Rf
cat ${PONAME}.txt | sed 's/$/-en-US/' | xargs mkdir
mkdir other-licenses-en-US/branding

cd ${HOME}/seal/$SRCDIR/mozilla-aurora
cp -Rf browser/locales/en-US/* ${ANSEO}/browser-en-US
cp -Rf browser/metro/locales/en-US ${ANSEO}/browser-en-US/metro
cp -Rf dom/locales/en-US/* ${ANSEO}/dom-en-US
#cp -Rf embedding/android/locales/en-US ${ANSEO}/embedding-en-US/android
cp -Rf mobile/locales/en-US/* ${ANSEO}/mobile-en-US
cp -Rf mobile/android/locales/en-US ${ANSEO}/mobile-en-US/android
cp -Rf mobile/android/base/locales/en-US ${ANSEO}/mobile-en-US/android/base
#cp -Rf mobile/xul/locales/en-US ${ANSEO}/mobile-en-US/xul
cp -Rf netwerk/locales/en-US/* ${ANSEO}/netwerk-en-US
cp -Rf security/manager/locales/en-US ${ANSEO}/security-en-US/manager
cp -Rf services/sync/locales/en-US ${ANSEO}/services-en-US/sync
cp -Rf toolkit/locales/en-US/* ${ANSEO}/toolkit-en-US
cp -Rf webapprt/locales/en-US/* ${ANSEO}/webapprt-en-US

cd ${HOME}/seal/$SRCDIR/comm-aurora
cp -Rf calendar/locales/en-US/* ${ANSEO}/calendar-en-US
cp -Rf chat/locales/en-US/* ${ANSEO}/chat-en-US
cp -Rf editor/ui/locales/en-US ${ANSEO}/editor-en-US/ui
cp -Rf mail/locales/en-US/* ${ANSEO}/mail-en-US
cp -Rf other-licenses/branding/thunderbird/locales/en-US ${ANSEO}/other-licenses-en-US/branding/thunderbird
#cp -Rf other-licenses/branding/sunbird/locales/en-US ${ANSEO}/other-licenses-en-US/branding/sunbird

cd ${HOME}/seal/gaia
cp -Rf en-US/* ${ANSEO}/gaia-en-US
sed -i "s/^deny=\(Don.*\)$/dontallow=\1/" ${ANSEO}/gaia-en-US/apps/system/system.properties
cd ${ANSEO}

# HACKS until these files are cleaned up in CVS or translate toolkit works
sed -i '/^<!-- commenting/d; /<!ENTITY messagesHeader.label/d' mail-en-US/chrome/messenger/subscribe.dtd
# next two lines reinserted into ga-IE dtd after translation
#sed -i '1,3d' browser-en-US/chrome/overrides/netError.dtd
#sed -i '1,3d' browser-en-US/chrome/browser/aboutCertError.dtd
#sed -i '1,3d' mobile-en-US/chrome/aboutCertError.dtd

# set up variables in makefile; need "VERSION" correct
# before translation starts since moznua needs it
sed -i "/^VERSION/s/.*/VERSION=$PONAME/" makefile
sed -i "/^CVSDIREC/s/.*/CVSDIREC=$SRCDIR/" makefile

make obair.po

cpo -q *${PONAME}.ga.po
cpo -q cal_obair.po obair.po tb_obair.po gaia_obair.po

echo "Finish translating the obair files, copy to -trunk.ga.po files"
echo "Then do a 'make' to build Irish dtd/properties and copy to hg"
