#!/bin/bash
echo "Applying sed tweaks..."
FULLPATH="${1}"   # passed on from mozdist

sed -i '/^VK/s/\\\\u/\\u/' toolkit-ga-IE/chrome/global-platform/mac/platformKeys.properties
#sed -i '/^monthDate/s/.*/monthDate=#2 #1/' toolkit-ga-IE/chrome/mozapps/downloads/downloads.properties

# comments in this file before this field.   need to increment now and again
sed -i '/=Bing/d' browser-ga-IE/chrome/browser-region/region.properties
sed -i '/^gecko.handlerService.defaultHandlersVersion/s/.*/gecko.handlerService.defaultHandlersVersion=2/' browser-ga-IE/chrome/browser-region/region.properties
sed -i 's/name=Mibbit/name = Mibbit/' browser-ga-IE/chrome/browser-region/region.properties
sed -i '/mibbit\.com/s/late=https/late = https/' browser-ga-IE/chrome/browser-region/region.properties
sed -i '/The default set of protocol handlers for irc:/s/.*/\n&/' browser-ga-IE/chrome/browser-region/region.properties
sed -i '/^gecko.handlerService.schemes.mailto.0.uriTemplate/s/ *$//' browser-ga-IE/chrome/browser-region/region.properties
if [ ! "${FULLPATH}" = "${HOME}/seal/moz-1.9.2/ga-IE" -a ! "${FULLPATH}" = "${HOME}/seal/moz-2.0/ga-IE" ]
then
	sed -i '1s/.*/# LOCALIZATION NOTE: REVIEW_REQUIRED\n# Please do not commit any changes to this file without a review from\n# the l10n-drivers team (this includes en-US). In order to get one,\n# please file a bug, add the "productization" keyword and CC l10n@mozilla.com.\n\n&/' browser-ga-IE/chrome/browser-region/region.properties
fi

# see bug 833344 (really should upgrade translate toolkit)
#sed -i 's/\(.\)#/\1\n#/g' browser-ga-IE/profile/bookmarks.inc mobile-ga-IE/profile/bookmarks.inc mobile-ga-IE/xul/defines.inc mobile-ga-IE/android/defines.inc


sed -i '/^notifyBarNotNowButtonText/s/=.*$/=Ná Meabhraigh anois/; /^notifyBarChangeButtonAccessKey/s/=.$/=A/; /^notifyBarDontChangeButtonAccessKey/s/=.$/=N/' toolkit-ga-IE/chrome/passwordmgr/passwordmgr.properties

# WINDOW SIZES!
sed -i 's/\(ENTITY window\..*idth\).*/\1 "50em">/' browser-ga-IE/chrome/browser/preferences/connection.dtd
sed -i 's/\(ENTITY window\..*idth\).*/\1 "48em">/' browser-ga-IE/chrome/browser/preferences/fonts.dtd
sed -i '/prefWindow\.styleWin /s/height: ..em/height: 40em/' browser-ga-IE/chrome/browser/preferences/preferences.dtd
sed -i '/^telemetryYesButtonAccessKey/s/.*/telemetryYesButtonAccessKey = T/' mail-ga-IE/chrome/messenger/telemetry.properties browser-ga-IE/chrome/browser/browser.properties
sed -i '/^social.toggle.accesskey/s/.*/social.toggle.accesskey = a/' browser-ga-IE/chrome/browser/browser.properties
sed -i '/^view.sortBy.date.accesskey/s/.*/view.sortBy.date.accesskey=r/' browser-ga-IE/chrome/browser/places/places.properties
sed -i '/^view.sortBy.keyword.accesskey/s/.*/view.sortBy.keyword.accesskey=g/' browser-ga-IE/chrome/browser/places/places.properties
sed -i '/^view.sortBy.lastModified.accesskey/s/.*/view.sortBy.lastModified.accesskey=A/' browser-ga-IE/chrome/browser/places/places.properties

# commandkey problems - don't want any translated - routine now is
# to leave single letters untranslated in PO and then fix the accesskeys
# that need fixing
sed -i 's/^hideButton.accesskey.*/hideButton.accesskey=F/' toolkit-ga-IE/chrome/mozapps/update/updates.properties
sed -i '/^pluginInstallation.close.accesskey/s/.*/pluginInstallation.close.accesskey=D/' toolkit-ga-IE/chrome/mozapps/plugins/plugins.properties
sed -i '/^pluginInstallation.restart.accesskey/s/.*/pluginInstallation.restart.accesskey=A/' toolkit-ga-IE/chrome/mozapps/plugins/plugins.properties
sed -i '/^cmd.purchaseAddon.accesskey/s/.*/cmd.purchaseAddon.accesskey=C/' toolkit-ga-IE/chrome/mozapps/extensions/extensions.properties

sed -i 's/certs.ask.accesskey "."/certs.ask.accesskey "d"/; s/certs.auto.accesskey "."/certs.auto.accesskey "u"/' browser-ga-IE/chrome/browser/preferences/advanced.dtd
sed -i 's/urlbar.accesskey "."/urlbar.accesskey "m"/; s/selectAllCmd.key "."/selectAllCmd.key "A"/; s/searchFocus.commandkey2 "."/searchFocus.commandkey2 "e"/; s/findAgainCmd.commandkey "."/findAgainCmd.commandkey "g"/' browser-ga-IE/chrome/browser/browser.dtd
sed -i 's/mediaSaveAs.accesskey "."/mediaSaveAs.accesskey "S"/' browser-ga-IE/chrome/browser/pageInfo.dtd
sed -i 's/mediaTab.accesskey "."/mediaTab.accesskey "M"/' browser-ga-IE/chrome/browser/pageInfo.dtd
sed -i 's/generalSecurityDetails.accesskey "."/generalSecurityDetails.accesskey "M"/' browser-ga-IE/chrome/browser/pageInfo.dtd
sed -i 's/permTab.accesskey "."/permTab.accesskey "C"/' browser-ga-IE/chrome/browser/pageInfo.dtd
sed -i 's/feedSubscribe.accesskey "."/feedSubscribe.accesskey "L"/' browser-ga-IE/chrome/browser/pageInfo.dtd
sed -i 's/clearTimeDuration.accesskey "."/clearTimeDuration.accesskey "R"/' browser-ga-IE/chrome/browser/sanitize.dtd
sed -i 's/selectAllCmd.key "."/selectAllCmd.key "A"/' toolkit-ga-IE/chrome/global/editMenuOverlay.dtd
sed -i '
s/printCmd.commandkey "."/printCmd.commandkey "P"/
s/findAgainCmd.commandkey "."/findAgainCmd.commandkey "g"/
' toolkit-ga-IE/chrome/global/viewSource.dtd
sed -i 's/JoinCellAccesskey=.*/JoinCellAccesskey=C/' editor-ga-IE/ui/chrome/composer/editor.properties
sed -i '
s/filepreview.accesskey "."/filepreview.accesskey "B"/
s/sendPage.accesskey "."/sendPage.accesskey "S"/
s/fileprintsetup.accesskey "."/fileprintsetup.accesskey "c"/
s/fileclose.accesskey "."/fileclose.accesskey "D"/
s/pasteImage.accesskey "."/pasteImage.accesskey "m"/
s/editpastelink.accesskey "."/editpastelink.accesskey "N"/
s/insertlink.accesskey "."/insertlink.accesskey "N"/
s/insertimage.accesskey "."/insertimage.accesskey "m"/
s/delete.accesskey "."/delete.accesskey "S"/
s/clear.accesskey "."/clear.accesskey "B"/
s/size-xx-small.accesskey "."/size-xx-small.accesskey "f"/
s/size-x-small.accesskey "."/size-x-small.accesskey "a"/
s/size-small.accesskey "."/size-small.accesskey "b"/
s/size-medium.accesskey "."/size-medium.accesskey "s"/
s/size-large.accesskey "."/size-large.accesskey "m"/
s/listdefinition.accesskey "."/listdefinition.accesskey "S"/
s/alignjustify.accesskey "."/alignjustify.accesskey "C"/
s/heading1.accesskey "11"/heading1.accesskey "1"/
' editor-ga-IE/ui/chrome/composer/editorOverlay.dtd
sed -i 's/newMessageCmd.key "."/newMessageCmd.key "M"/' mail-ga-IE/chrome/messenger/mailOverlay.dtd
sed -i 's/messengerCmd.commandkey "11"/messengerCmd.commandkey "1"/' mail-ga-IE/chrome/messenger/messengercompose/messengercompose.dtd mail-ga-IE/chrome/messenger/messenger.dtd mail-ga-IE/chrome/messenger/addressbook/abMainWindow.dtd
sed -i '
s/forwardMsgCmd.label "[^"]*"/forwardMsgCmd.label "Cuir Ar Aghaidh"/
s/forwardMsgCmd.accesskey "."/forwardMsgCmd.accesskey "C"/
s/contextForward.label "[^"]*"/contextForward.label "Cuir Ar Aghaidh"/
s/contextForward.accesskey "."/contextForward.accesskey "C"/
s/forwardButton.label "[^"]*"/forwardButton.label "Cuir Ar Aghaidh"/
s/findAgainCmd.key "."/findAgainCmd.key "g"/
s/findPrevCmd.key "."/findPrevCmd.key "g"/
s/editMsgAsNewCmd.key "."/editMsgAsNewCmd.key "e"/
s/tagCmd1.key "11"/tagCmd1.key "1"/
' mail-ga-IE/chrome/messenger/messenger.dtd
sed -i '
s/newMessageCmd.key "."/newMessageCmd.key "M"/
s/selectAllCmd.key "."/selectAllCmd.key "A"/
' mail-ga-IE/chrome/messenger/addressbook/abMainWindow.dtd
sed -i '
s/newMessage.key "."/newMessage.key "M"/
s/printCmd.key "."/printCmd.key "P"/
s/selectAllCmd.key "."/selectAllCmd.key "A"/
' mail-ga-IE/chrome/messenger/messengercompose/messengercompose.dtd
sed -i '
s/AddPlainText.accesskey "."/AddPlainText.accesskey "C"/
s/add.htmldomain.accesskey "."/add.htmldomain.accesskey "H"/
s/add.plaintext.accesskey "."/add.plaintext.accesskey "G"/
' mail-ga-IE/chrome/messenger/preferences/sendoptions.dtd

sed -i 's/priority.level.medium.accesskey "."/priority.level.medium.accesskey "M"/; s/priority.level.high.accesskey "."/priority.level.high.accesskey "A"/; s/calendar.dayview.accesskey "."/calendar.dayview.accesskey "L"/; s/calendar.weekview.accesskey "."/calendar.weekview.accesskey "S"/; s/calendar.monthview.accesskey "."/calendar.monthview.accesskey "M"/; s/calendar.menu.options.close.accesskey "."/calendar.menu.options.close.accesskey "D"/; s/week.short "."/week.short "S"/' calendar-ga-IE/chrome/calendar/calendar.dtd
sed -i 's/calendar.dayView.key "11"/calendar.dayView.key "1"/' calendar-ga-IE/chrome/calendar/calendar.dtd
sed -i 's/progress.level.100.accesskey "11"/progress.level.100.accesskey "1"/' calendar-ga-IE/chrome/calendar/calendar.dtd
sed -i 's/^likelyTimezone.*/likelyTimezone=Europe\/Dublin/' calendar-ga-IE/chrome/calendar/calendar.properties
sed -i 's/^last1=.*/last1=seo caite/; s/^last2=.*/last2=seo caite/' calendar-ga-IE/chrome/calendar/calendar.properties
sed -i 's/event\.recurrence\.of\.label .*/event.recurrence.of.label "de">/; s/event.freebusy.legend.free ".*/event.freebusy.legend.free "Saor">/' calendar-ga-IE/chrome/calendar/calendar-event-dialog.dtd
sed -i '/^pluralForWeekdays=/s/.*/pluralForWeekdays=false/' calendar-ga-IE/chrome/calendar/calendar-event-dialog.properties
sed -i '
s/day.1.Ddd.accesskey "."/day.1.Ddd.accesskey "D"/
s/day.2.Ddd.accesskey "."/day.2.Ddd.accesskey "L"/
s/day.3.Ddd.accesskey "."/day.3.Ddd.accesskey "M"/
s/day.4.Ddd.accesskey "."/day.4.Ddd.accesskey "C"/
s/day.5.Ddd.accesskey "."/day.5.Ddd.accesskey "r"/
s/day.6.Ddd.accesskey "."/day.6.Ddd.accesskey "A"/
s/day.7.Ddd.accesskey "."/day.7.Ddd.accesskey "S"/
' calendar-ga-IE/chrome/calendar/global.dtd
sed -i '
s/^day.1.short=.*/day.1.short=D/
s/^day.2.short=.*/day.2.short=L/
s/^day.3.short=.*/day.3.short=M/
s/^day.4.short=.*/day.4.short=C/
s/^day.5.short=.*/day.5.short=D/
s/^day.6.short=.*/day.6.short=A/
s/^day.7.short=.*/day.7.short=S/
s/^month.5.Mmm=.*/month.5.Mmm=Bea/
' calendar-ga-IE/chrome/calendar/dateFormat.properties toolkit-ga-IE/chrome/global/dateFormat.properties

sed -i 's/event.delete.event.accesskey "."/event.delete.event.accesskey "R"/' calendar-ga-IE/chrome/calendar/menuOverlay.dtd

sed -i '
s/"End"/"Deireadh"/
s/newevent.before.label "[^"]*"/newevent.before.label "roimhe"/
s/newevent.after.label "[^"]*"/newevent.after.label "ina dhiaidh"/
' calendar-ga-IE/chrome/calendar/calendar.dtd

sed -i '
s/window.width "..em"/window.width "42em"/
s/window.macWidth "..em"/window.macWidth "45em"/
' calendar-ga-IE/chrome/calendar/preferences/connection.dtd

#sed -i '
#s/inspectReturnNew.label "[^"]*"/inspectReturnNew.label "i bhfuinneog nua"/
#' extensions-ga-IE/inspector/resources/viewers/jsObject.dtd

sed -i 's/exceptionMgr.certstatus.accesskey "."/exceptionMgr.certstatus.accesskey "A"/' security-ga-IE/manager/chrome/pippki/certManager.dtd
sed -i 's/loaddevice.modname.accesskey "."/loaddevice.modname.accesskey "A"/' security-ga-IE/manager/chrome/pippki/deviceManager.dtd
sed -i 's/loaddevice.filename.accesskey "."/loaddevice.filename.accesskey "c"/' security-ga-IE/manager/chrome/pippki/deviceManager.dtd

sed -i 's/cmd.about.accesskey "."/cmd.about.accesskey "M"/' toolkit-ga-IE/chrome/mozapps/extensions/extensions.dtd
# still need these two with latest translate toolkit
sed -i '/^VK_HOME/s/.*/VK_HOME=Home/' toolkit-ga-IE/chrome/global/keys.properties
LC_ALL=C sed -i '
/^ar *=/s/.*/ar = Araibis/
/^bn *=/s/.*/bn = Beangáilis/
/^el *=/s/.*/el = Gréigis/
/^gu *=/s/.*/gu = Gúisearáitis/
/^he *=/s/.*/he = Eabhrais/
/^hy *=/s/.*/hy = Airméinis/
/^ja *=/s/.*/ja = Seapáinis/
/^ka *=/s/.*/ka = Seoirsis/
/^km *=/s/.*/km = Ciméiris/
/^ko *=/s/.*/ko = Cóiréis/
/^ml *=/s/.*/ml = Mailéalaimis/
/^ru *=/s/.*/ru = Rúisis/
/^ta *=/s/.*/ta = Tamailis/
/^th *=/s/.*/th = Téalainnis/
/^tr *=/s/.*/tr = Tuircis/
/^uk *=/s/.*/uk = Úcráinis/
/^zh *=/s/.*/zh = Sínis/
' toolkit-ga-IE/chrome/global/languageNames.properties

#sed -i '
#s/credit.translation ""/credit.translation "<h3>Aistritheoirí<\/h3><ul><li>Marion Gunn<\/li><li>Séamus Ó Ciardhuáin<\/li><li>Kevin Scannell<\/li><\/ul>"/
##' calendar-ga-IE/chrome/calendar/aboutDialog.dtd
