#!/bin/bash
# posted by Vincent Béron to the mozilla-l10n mailing list
#  and tweaked by Kevin Scannell 20 Sept 2004 to work with 
#  gaeilge.mozdev CVS structure
MOZCVS=${HOME}/gaeilge/gnu/mozilla
BUILDDIR=${MOZCVS}/gaeilge/src/langpack-build-dir
rm -Rf ${BUILDDIR}
MBL=${MOZCVS}/gaeilge/src/browser-ga-IE   # mozilla/browser/locales/en-US
MTL=${MOZCVS}/gaeilge/src/toolkit-ga-IE   # mozilla/toolkit/locales/en-US
mkdir -p langpack-build-dir/chrome/locale
cd ${MBL}/chrome
cp -R browser browser-region cookie global ${BUILDDIR}/chrome/locale
cd ${MOZCVS}/mozilla/browser/locales/generic/chrome
# help? inspector?
cp -R browser browser-region cookie ${BUILDDIR}/chrome/locale
cd ..
cp install.rdf ${BUILDDIR}/install.rdf-orig
cd ${MTL}/chrome
cp -R global global-platform global-region mozapps necko passwordmgr pipnss pippki ${BUILDDIR}/chrome/locale
cd ${MOZCVS}/mozilla/toolkit/locales/generic/chrome
cp -R global global-platform global-region mozapps necko passwordmgr pipnss pippki ${BUILDDIR}/chrome/locale
cd ${BUILDDIR}/chrome/locale
rm -rf `find . -name 'CVS'`
export AB_CD=ga-IE
export MOZ_LOC_VER=1.7
export MOZ_REG_VER=1.7
export APP_VERSION=1.7
# generated on borel using uuidgen
export MOZ_LANGPACK_EID="{906b5382-9a34-4ab1-a627-39487b0678a9}"
export MOZ_LANGPACK_CREATOR="mozilla.org"
# (Use the same format as in browser/locales/en-US/defines.inc)
export MOZ_LANGPACK_CONTRIBUTORS="<em:contributor>Kevin Scannell<\/em:contributor> <em:contributor>Brian King<\/em:contributor> <em:contributor>Marion Gunn<\/em:contributor>"
export MOZ_LANG_TITLE="Irish (IE)"
for DIR in browser browser-region cookie global global-platform global-region mozapps necko passwordmgr pipnss pippki; do
	cd $DIR;
	mv contents.rdf contents.rdf-orig;
# First we remove the comments, then we replace @AB_CD@,
# @MOZILLA_LOCALE_VERSION@, then we replace @MOZILLA_REGION_VERSION@,
# then we replace @MOZ_LANG_TITLE@
	grep -v "^#" contents.rdf-orig |\
		sed -e "s/@AB_CD@/$AB_CD/g" - |\
		sed -e "s/@MOZILLA_LOCALE_VERSION@/$MOZ_LOC_VER/g" - |\
		sed -e "s/@MOZILLA_REGION_VERSION@/$MOZ_REG_VER/g" - |\
		sed -e "s/@MOZ_LANG_TITLE@/$MOZ_LANG_TITLE/g" - >\
		contents.rdf;
	rm contents.rdf-orig;
	cd ..;
done

cd ..
zip -0rD -q $AB_CD.jar locale
cd ..

# (autoconfig is not present by default in FF nightlies and releases, so remove it)
grep -v "^#" install.rdf-orig |\
	grep -v autoconfig - |\
	sed -e "s/@MOZ_LANGPACK_EID@/$MOZ_LANGPACK_EID/g" - |\
	sed -e "s/@MOZ_LANG_TITLE@/$MOZ_LANG_TITLE/g" - |\
	sed -e "s/@APP_VERSION@/$APP_VERSION/g" - |\
	sed -e "s/@MOZ_LANGPACK_CREATOR@/$MOZ_LANGPACK_CREATOR/g" - |\
	sed -e \
"s/@MOZ_LANGPACK_CONTRIBUTORS@/$MOZ_LANGPACK_CONTRIBUTORS/g" - |\
	sed -e "s/@AB_CD@/$AB_CD/g" - >\
	install.rdf

rm install.rdf-orig
zip -9D -q langpack-$AB_CD.xpi install.rdf chrome/$AB_CD.jar
