#!/bin/bash
# posted by Vincent Béron to the mozilla-l10n mailing list
#  and tweaked by Kevin Scannell 20 Sept 2004 to work with 
#  gaeilge.mozdev CVS structure
export IRISH_VERSION=0.7.8

MOZCVS=${HOME}/gaeilge/gnu/mozilla
BUILDDIR=${MOZCVS}/gaeilge/src/langpack-build-dir
rm -Rf ${BUILDDIR}
MBL=${MOZCVS}/gaeilge/src/browser-ga-IE   # mozilla/browser/locales/en-US
MTL=${MOZCVS}/gaeilge/src/toolkit-ga-IE   # mozilla/toolkit/locales/en-US
mkdir -p langpack-build-dir/chrome/locale
cd ${MBL}/chrome
cp -R browser browser-region cookie global ${BUILDDIR}/chrome/locale

#   can uncomment subsets of lines below for debugging;
#cd ${MOZCVS}/gaeilge/src/browser-en-US/chrome
# cp -R browser ${BUILDDIR}/chrome/locale

#cp browser/browser.dtd ${BUILDDIR}/chrome/locale/browser
#cp browser/aboutDialog.dtd ${BUILDDIR}/chrome/locale/browser
#cp browser/credits.dtd ${BUILDDIR}/chrome/locale/browser
#cp browser/metaData.dtd ${BUILDDIR}/chrome/locale/browser
#cp browser/openLocation.dtd ${BUILDDIR}/chrome/locale/browser
#cp browser/page-drawer.dtd ${BUILDDIR}/chrome/locale/browser
#cp browser/pageInfo.dtd ${BUILDDIR}/chrome/locale/browser
#cp browser/pageReport.dtd ${BUILDDIR}/chrome/locale/browser
#cp browser/pageReportFirstTime.dtd ${BUILDDIR}/chrome/locale/browser
#cp browser/setWallpaper.dtd ${BUILDDIR}/chrome/locale/browser

#cp browser/*.properties ${BUILDDIR}/chrome/locale/browser
#cp -R browser/bookmarks ${BUILDDIR}/chrome/locale/browser
#cp -R browser/cookieviewer ${BUILDDIR}/chrome/locale/browser
#cp -R browser/history ${BUILDDIR}/chrome/locale/browser
#cp -R browser/migration ${BUILDDIR}/chrome/locale/browser
#cp -R browser/pref ${BUILDDIR}/chrome/locale/browser
#cp -R browser/sidebar ${BUILDDIR}/chrome/locale/browser

cd ${MOZCVS}/mozilla/browser/locales/generic/chrome
# next line didn't have help/inspector in V.B. version;
# only stuff we're copying with this are the contents.rdf...
#  adding either seems to cause bugs
cp -R browser browser-region cookie ${BUILDDIR}/chrome/locale
# cd ..
# cp install.rdf ${BUILDDIR}/install.rdf-orig
cd ${MTL}/chrome
cp -R global global-platform global-region mozapps necko passwordmgr pipnss pippki ${BUILDDIR}/chrome/locale
cd ${MOZCVS}/mozilla/toolkit/locales/generic/chrome
cp -R global global-platform global-region mozapps necko passwordmgr pipnss pippki ${BUILDDIR}/chrome/locale
cd ${BUILDDIR}/chrome/locale
rm -rf `find . -name 'CVS'`
export AB_CD=ga-IE
#  seems like these should all be the same, but I don't really understand
#  how they are used by chrome registry
export MOZ_LOC_VER=${IRISH_VERSION}
export MOZ_REG_VER=${IRISH_VERSION}
export APP_VERSION=${IRISH_VERSION}
# generated on borel using uuidgen
# export MOZ_LANGPACK_EID="{906b5382-9a34-4ab1-a627-39487b0678a9}"
# export MOZ_LANGPACK_CREATOR="mozilla.org"
# (Use the same format as in browser/locales/en-US/defines.inc)
export MOZ_LANG_TITLE="Irish (IE)"
for DIR in browser browser-region cookie global global-platform global-region mozapps necko passwordmgr pipnss pippki; do
	cd $DIR;
	mv contents.rdf contents.rdf-orig;
	grep -v "^#" contents.rdf-orig |\
		sed -e "s/@AB_CD@/$AB_CD/g" - |\
		sed -e "s/@MOZILLA_LOCALE_VERSION@/$MOZ_LOC_VER/g" - |\
		sed -e "s/@MOZILLA_REGION_VERSION@/$MOZ_REG_VER/g" - |\
		sed -e "s/@MOZ_LANG_TITLE@/$MOZ_LANG_TITLE/g" - >\
		contents.rdf;
	rm contents.rdf-orig;
	cd ..;
done

cd ..
zip -0rD -q $AB_CD.jar locale
cd ..

# (autoconfig is not present by default in FF nightlies and releases, so remove it)
## Next block is now defunct since we're using Brian's install.rdf 30 Sep 2004
# grep -v "^#" install.rdf-orig | grep -v "locale/inspector" | grep -v "locale/help" |\
# 	grep -v autoconfig - |\
# 	sed -e "s/@MOZ_LANGPACK_EID@/$MOZ_LANGPACK_EID/g" - |\
# 	sed -e "s/@MOZ_LANG_TITLE@/$MOZ_LANG_TITLE/g" - |\
# 	sed -e "s/@APP_VERSION@/$APP_VERSION/g" - |\
# 	sed -e "s/@MOZ_LANGPACK_CREATOR@/$MOZ_LANGPACK_CREATOR/g" - |\
# 	sed -e \
# "s/@MOZ_LANGPACK_CONTRIBUTORS@/$MOZ_LANGPACK_CONTRIBUTORS/g" - |\
# 	sed -e "s/@AB_CD@/$AB_CD/g" - >\
# 	install.rdf
# rm install.rdf-orig

cp ../install.rdf .
sed -i "s/@APP_VERSION@/$APP_VERSION/g" install.rdf
cat ../aistr.txt | sed 's/.*/    <em:contributor>&<\/em:contributor>/' | iconv -f iso-8859-1 -t utf8 > aistr.8.txt
sed -i "/The Irish Mozilla Localisation Team/r aistr.8.txt" install.rdf
rm -f aistr.8.txt
zip -9D -q langpack-$AB_CD.xpi install.rdf chrome/$AB_CD.jar
